server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.124.3/1811emp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver


